import React from 'react'
import { Users, Percent, Award, ShieldCheck } from 'lucide-react'

const NetworkSection = ({ networkRef }) => {
  return (
    <section 
      id="network" 
      ref={networkRef}
      className="relative z-10 py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto"
    >
      <div 
        className="absolute inset-x-4 inset-y-12 bg-cover bg-center rounded-3xl opacity-5 pointer-events-none z-0" 
        style={{ backgroundImage: `url('/images/img_20.jpg')` }}
      ></div>

      <div className="relative z-10">
        <div className="text-center space-y-3 mb-16">
          <div className="inline-flex items-center gap-1 px-3 py-1 rounded-full bg-gold-dark/10 border border-gold-medium/10 text-gold-light text-[10px] font-bold uppercase tracking-widest">
            <Users className="w-3.5 h-3.5 text-gold-medium" /> Partner Network
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold font-display text-white">
            The Elite Partner Alliance
          </h2>
          <p className="text-sm text-gray-500 max-w-md mx-auto leading-relaxed">
            Unlock residual community rewards by inviting, educating, and co-trading with your private network circle.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Left Side */}
          <div className="lg:col-span-6 space-y-6">
            <div className="space-y-2">
              <span className="text-[10px] uppercase font-bold tracking-widest text-gold-medium">Synergetic Network Growth</span>
              <h3 className="text-2xl font-bold text-white">Multi-Tier Binary Community System</h3>
              <p className="text-sm text-gray-400 leading-relaxed font-light">
                Build a community of dedicated traders and earn matching bonuses based on institutional course acquisitions and active trading pools inside your left and right network structures.
              </p>
            </div>

            <div className="space-y-4 pt-2">
              <div className="flex gap-4 p-4 rounded-xl border border-gold-dark/10 bg-dark-900/30">
                <div className="w-10 h-10 rounded-lg bg-gold-dark/20 border border-gold-medium/30 flex items-center justify-center text-gold-light shrink-0">
                  <Percent className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-white">10% Direct Alliance Reward</h4>
                  <p className="text-xs text-gray-500">Earn direct dividends immediately when your network members acquire any Trading Academy course tier.</p>
                </div>
              </div>

              <div className="flex gap-4 p-4 rounded-xl border border-gold-dark/10 bg-dark-900/30">
                <div className="w-10 h-10 rounded-lg bg-gold-dark/20 border border-gold-medium/30 flex items-center justify-center text-gold-light shrink-0">
                  <Users className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-white">8% Binary Team Matching</h4>
                  <p className="text-xs text-gray-500">Earn dynamic performance overrides when binary volume balances match across your network wings.</p>
                </div>
              </div>

              <div className="flex gap-4 p-4 rounded-xl border border-gold-dark/10 bg-dark-900/30">
                <div className="w-10 h-10 rounded-lg bg-gold-dark/20 border border-gold-medium/30 flex items-center justify-center text-gold-light shrink-0">
                  <Award className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-white">Global Trading Pool Dividend</h4>
                  <p className="text-xs text-gray-500">Elite members unlock fractional access to global proprietary trading gains generated by our algorithm pool.</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right Side */}
          <div className="lg:col-span-6 space-y-6">
            <h3 className="text-lg font-bold font-display uppercase tracking-widest text-gold-light border-b border-gold-dark/10 pb-3">
              Partner Rank Advancement Structure
            </h3>
            
            <div className="grid grid-cols-1 sm:grid-cols-5 gap-4">
              
              <div className="rank-badge bg-dark-900 border border-gold-dark/10 hover:border-gold-medium/30 p-4 rounded-xl text-center space-y-2 transition-all">
                <div className="w-10 h-10 rounded-full bg-amber-900/20 border border-amber-900 text-amber-600 flex items-center justify-center mx-auto text-xs font-bold font-mono">1</div>
                <div>
                  <span className="block text-xs font-bold text-white leading-tight">Bronze Colt</span>
                  <span className="text-[9px] text-gray-500">Entry Level</span>
                </div>
                <div className="text-[9px] font-semibold text-gold-light bg-gold-dark/10 py-0.5 rounded">Active</div>
              </div>

              <div className="rank-badge bg-dark-900 border border-gold-dark/10 hover:border-gold-medium/30 p-4 rounded-xl text-center space-y-2 transition-all">
                <div className="w-10 h-10 rounded-full bg-slate-700/20 border border-slate-500 text-slate-300 flex items-center justify-center mx-auto text-xs font-bold font-mono">2</div>
                <div>
                  <span className="block text-xs font-bold text-white leading-tight">Silver Stallion</span>
                  <span className="text-[9px] text-gray-500">Refer 3</span>
                </div>
                <div className="text-[9px] font-semibold text-gold-light bg-gold-dark/10 py-0.5 rounded">5% Extra</div>
              </div>

              <div className="rank-badge bg-dark-900 border border-gold-dark/15 hover:border-gold-medium/30 p-4 rounded-xl text-center space-y-2 transition-all glow-gold">
                <div className="w-10 h-10 rounded-full bg-amber-500/20 border border-gold-medium text-gold-light flex items-center justify-center mx-auto text-xs font-bold font-mono">3</div>
                <div>
                  <span className="block text-xs font-bold text-white leading-tight">Gold Mustang</span>
                  <span className="text-[9px] text-gray-500">5k Vol</span>
                </div>
                <div className="text-[9px] font-semibold text-gold-light bg-gold-dark/15 py-0.5 rounded">Pool Access</div>
              </div>

              <div className="rank-badge bg-dark-900 border border-gold-dark/10 hover:border-gold-medium/30 p-4 rounded-xl text-center space-y-2 transition-all">
                <div className="w-10 h-10 rounded-full bg-sky-500/20 border border-sky-400 text-sky-300 flex items-center justify-center mx-auto text-xs font-bold font-mono">4</div>
                <div>
                  <span className="block text-xs font-bold text-white leading-tight">Diamond Pegasus</span>
                  <span className="text-[9px] text-gray-500">20k Vol</span>
                </div>
                <div className="text-[9px] font-semibold text-gold-light bg-gold-dark/10 py-0.5 rounded">VIP Lounge</div>
              </div>

              <div className="rank-badge bg-gradient-to-b from-dark-900 to-gold-dark/20 border border-gold-medium/40 p-4 rounded-xl text-center space-y-2 transition-all">
                <div className="w-10 h-10 rounded-full bg-gold-medium/30 border-2 border-gold-light text-white flex items-center justify-center mx-auto text-xs font-bold font-mono animate-bounce">★</div>
                <div>
                  <span className="block text-xs font-bold text-white leading-tight">Dark Horse</span>
                  <span className="text-[9px] text-gray-400">100k Vol</span>
                </div>
                <div className="text-[9px] font-bold text-black bg-gold-medium py-0.5 rounded">Global Board</div>
              </div>

            </div>

            <div className="p-4 rounded-xl bg-gold-dark/5 border border-gold-dark/10 text-xs leading-relaxed text-gray-500 flex gap-2.5">
              <ShieldCheck className="w-5 h-5 text-gold-medium shrink-0 mt-0.5" />
              <span>Our partner network strictly adheres to institutional sales metrics. All advancement points, rewards, and binary bonuses are calculated based on course packages acquired and educational milestones achieved by the network. No trading deposits are utilized for referral calculations.</span>
            </div>
          </div>

        </div>
      </div>
    </section>
  )
}

export default NetworkSection
